id: limu_training
title: 军队训练
description: 李牧将军向你汇报军队训练情况
speaker: 李牧
dialogue: 陛下，新兵训练进展顺利，但军费开支颇大，不知...
characterClues:
  revealedTraits:
    - 务实
    - 节俭
  personalityHints:
    - 李牧对军费管理很谨慎
    - 他关心普通士兵的生活
  backgroundHints:
    - 李牧亲自参与训练，深受士兵爱戴
activationConditions:
  minReignYears: 2
  maxReignYears: 15
  attributeRequirements:
    minMilitary: 40
weight: 6
removalConditions:
  maxMilitary: 30
options:
  - description: （待补充）
    target: player
    attribute: power
    offset: 0
  - description: （待补充）
    target: player
    attribute: power
    offset: 0
